name: Daily Run

on:
  push:
  schedule:
    - cron: "0 15 */1 * *"

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Deno Run
        timeout-minutes: 20
        run: |
          deno run -q -A src/index.ts
        env:
          TZ: "Asia/Tokyo"
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MASTODON_TOOT_MAX_LENGTH: ${{ vars.MASTODON_TOOT_MAX_LENGTH }}
          MASTODON_TARGET_ACCT: ${{ vars.MASTODON_TARGET_ACCT }}
          MASTODON_BOT_HOST: ${{ vars.MASTODON_BOT_HOST }}
          MASTODON_BOT_TOKEN: ${{ secrets.MASTODON_BOT_TOKEN }}
